import sys
import os
sys.path.append(os.path.abspath(r"""C:/RoboDK/Posts/""")) # temporarily add path to POSTS folder

from Fanuc_RJ3 import *

def p(x,y,z,r,p,w):
  a = r*math.pi/180.0
  b = p*math.pi/180.0
  c = w*math.pi/180.0
  ca = math.cos(a)
  sa = math.sin(a)
  cb = math.cos(b)
  sb = math.sin(b)
  cc = math.cos(c)
  sc = math.sin(c)
  return Mat([[cb*ca,ca*sc*sb-cc*sa,sc*sa+cc*ca*sb,x],[cb*sa,cc*ca+sc*sb*sa,cc*sb*sa-ca*sc,y],[-sb,cb*sc,cc*cb,z],[0.0,0.0,0.0,1.0]])

def make_program():
  print('Total instructions: 5')
  r = RobotPost(r"""Fanuc_RJ3""",r"""Fanuc M-710iC/45M""",6, axes_type=['R','R','R','R','R','R'], ip_com=r"""127.0.0.1""", api_port=20500, prog_ptr=2855706754336, robot_ptr=2855698194480)

  r.ProgStart(r"""Prog1""")
  r.RunMessage(r"""Program generated by RoboDK v5.1.3 for Fanuc M-710iC/45M on 26/11/2020 12:15:26""", True)
  r.RunMessage(r"""Using nominal kinematics.""", True)
  r.setFrame(p(0,0,0,0,0,0),-1,r"""Fanuc M-710iC/45M Base""")
  r.setTool(p(0,0,0,0,0,0),85,r"""Gripper RobotiQ 85 Opened""")
  r.MoveL(p(1555.71,882.304,203.381,33.0599,3.33571,175.663),[30,26.62,-37.35,5.45,-55.87,0],[0,0,0])
  r.RunMessage(r"""Attach to Gripper RobotiQ 85 Opened""", True)
  r.MoveJ(p(1334.1,-998.762,205.72,-36.82,0.67,-180),[-36.82,20.97,-39.53,0,-51.14,0],[0,0,0])
  r.RunMessage(r"""Detach from Gripper RobotiQ 85 Opened""", True)
  r.MoveJ(p(914.865,1284.96,178.137,54.55,4,-180),[54.55,18.37,-41.92,0,-52.08,0],[0,0,0])
  r.RunMessage(r"""Attach to Gripper RobotiQ 85 Opened""", True)
  r.MoveJ(p(982.673,-926.268,681.343,-44.5699,0.480769,-177.441),[-43.64,-3.56,-20.38,-2.73,-70.08,0],[0,0,0])
  r.MoveL(p(920.71,-1432.5,189.461,-57.27,-2.86,-180),[-57.27,22.51,-39.79,0,-47.35,0],[0,0,0])
  r.RunMessage(r"""Detach from Gripper RobotiQ 85 Opened""", True)
  r.ProgFinish(r"""Prog1""")
  r.ProgSave(r"""C:/Users/MarkK/Documents/RoboDK""",r"""Prog1""",True,r"""C:/RoboDK/Other/VSCodium/VSCodium.exe""")

if __name__ == "__main__":
  make_program()
